# Generated by Django 4.2.27 on 2026-01-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ocr_user', 'OCR用户'), ('normal_user', '普通用户')], default='normal_user', max_length=20, verbose_name='角色'),
        ),
    ]
