# Generated by Django 4.2.27 on 2026-01-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('access_key_id', models.CharField(max_length=200, verbose_name='AccessKeyId')),
                ('access_key_secret', models.CharField(max_length=200, verbose_name='AccessKeySecret')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OCR配置',
                'verbose_name_plural': 'OCR配置',
                'db_table': 'system_config',
            },
        ),
    ]
