# Generated by Django 4.2.27 on 2026-01-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(db_index=True, max_length=20, verbose_name='号牌号码')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('owner', models.CharField(blank=True, max_length=50, verbose_name='所有人')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住址')),
                ('chassis_number', models.CharField(blank=True, max_length=50, verbose_name='底盘号/机架号')),
                ('trailer_frame_number', models.CharField(blank=True, max_length=50, verbose_name='挂车架号码')),
                ('engine_number', models.CharField(blank=True, max_length=50, verbose_name='发动机号码')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='型号名称')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='登记日期')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('issue_authority', models.CharField(blank=True, max_length=100, verbose_name='发证机关')),
                ('tractor_min_weight', models.CharField(blank=True, max_length=50, verbose_name='拖拉机最小使用质量')),
                ('harvester_weight', models.CharField(blank=True, max_length=50, verbose_name='联合收割机质量')),
                ('tractor_max_load', models.CharField(blank=True, max_length=50, verbose_name='拖拉机最大允许载质量')),
                ('passenger_capacity', models.CharField(blank=True, max_length=20, verbose_name='准乘人数')),
                ('overall_dimension', models.CharField(blank=True, max_length=50, verbose_name='外廓尺寸(毫米)')),
                ('inspection_record', models.CharField(blank=True, max_length=200, verbose_name='检验记录')),
                ('brake_report_image', models.ImageField(blank=True, upload_to='inspection/brake/', verbose_name='制动性能检验报告图片')),
                ('headlight_report_image', models.ImageField(blank=True, upload_to='inspection/headlight/', verbose_name='前照灯检验报告图片')),
                ('body_color', models.CharField(blank=True, max_length=50, verbose_name='机身颜色')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ocr_raw_data', models.JSONField(blank=True, null=True, verbose_name='OCR原始数据')),
            ],
            options={
                'verbose_name': '检验记录',
                'verbose_name_plural': '检验记录',
                'db_table': 'inspection_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
