# Generated by Django 4.2.27 on 2026-01-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='license_back_image',
            field=models.ImageField(blank=True, upload_to='inspection/license/', verbose_name='行驶证副页图片'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='license_front_image',
            field=models.ImageField(blank=True, upload_to='inspection/license/', verbose_name='行驶证正面图片'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='plate_image',
            field=models.ImageField(blank=True, upload_to='inspection/plate/', verbose_name='车牌号图片'),
        ),
    ]
