# Generated by Django 4.2.27 on 2026-01-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_inspectionrecord_license_back_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionrecord',
            name='ocr_raw_data',
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='plate_ocr_result',
            field=models.CharField(blank=True, max_length=50, verbose_name='车牌识别结果'),
        ),
    ]
